"""Generate the host documentation from hosts/registry: docs/hosts/COMPATIBILITY.md, one guide per host
(docs/hosts/<id>.md, with any hand-written section from hosts/guides/<id>.md) and the README "Choose your AI tool"
table between its markers. `python install.py docs --check` fails when a generated file is out of date."""
from __future__ import annotations

from pathlib import Path

import hostkit as hk

DOCS = hk.ROOT / "docs" / "hosts"
GUIDES = hk.ROOT / "hosts" / "guides"
README = hk.ROOT / "README.md"
BEGIN, END = "<!-- hosts:begin (generated by python install.py docs) -->", "<!-- hosts:end -->"
RELEASE = "https://github.com/OzyAcc/design-dna/releases/latest/download/"
ICON = {"verified": "✅ verified", "partial": "🟡 partial", "untested": "⚪ untested", "not_applicable": "n/a", "failed": "❌ failed"}
KIND = {"skill-dir": "skill folder", "upload": "upload a zip", "plugin": "plugin / extension", "instructions": "instruction kit (fallback)"}


def status(h, stage) -> str:
    return ICON.get(h["testing"][stage]["status"], h["testing"][stage]["status"])


def methods(h) -> str:
    return ", ".join(dict.fromkeys(KIND[s["kind"]] for s in h["surfaces"]))


def first_step(h) -> str:
    kinds = {s["kind"] for s in h["surfaces"]}
    if "skill-dir" in kinds:
        return f"`python install.py install --target {h['id']}`"
    pkgs = [hk.package_kinds()[s["package"]][0] for s in h["surfaces"] if s.get("package")]
    return " · ".join(f"[{p}]({RELEASE}{p})" for p in dict.fromkeys(pkgs))


def furthest(reg, h) -> str:
    """The last stage, in order, that was verified without a gap before it; else the first partial stage."""
    done = None
    for st in reg["test_stages"]:
        status = h["testing"][st]["status"]
        if status == "verified":
            done = st
        elif status != "not_applicable":
            break
    if done:
        return f"✅ through {done}"
    part = next((st for st in reg["test_stages"] if h["testing"][st]["status"] == "partial"), None)
    return f"🟡 {part} (partial)" if part else "⚪ untested"


def readme_block(reg) -> str:
    rows = ["| AI tool | How it installs | Start here | Guide | Host test |", "|---|---|---|---|---|"]
    for h in reg["hosts"]:
        rows.append(f"| **{h['name']}** | {methods(h)} | {first_step(h)} | [guide](docs/hosts/{h['id']}.md) | {furthest(reg, h)} |")
    return "\n".join([BEGIN, "", *rows, "", END])


def compatibility(reg) -> str:
    L = ["# Compatibility registry", "",
         f"Generated from [`hosts/registry/`](../../hosts/registry/) by `python install.py docs`. Documentation checked "
         f"{reg['checked']}. AI-host results only: operating-system test results are in [BUILD-REPORT](../BUILD-REPORT.md) "
         "and [CAPABILITIES](../../CAPABILITIES.md); installer results per operating system are in [EVIDENCE](EVIDENCE.md).", "",
         "## Hosts", "",
         "| Host | Surfaces | Install method | Skill folder (user / project) | Capability |", "|---|---|---|---|---|"]
    for h in reg["hosts"]:
        dirs = f"`{h['skill_dirs']['user']}` / `{h['skill_dirs']['project']}`" if "skill_dirs" in h else "—"
        caps = ", ".join(dict.fromkeys(reg["capability_classes"][s["capability"]]["label"] for s in h["surfaces"]))
        L.append(f"| [{h['name']}]({h['id']}.md) | {len(h['surfaces'])} | {methods(h)} | {dirs} | {caps} |")
    L += ["", "## Host test results", "",
          "Stages: **install** (the package lands where the host looks), **discovery** (the host lists the skill), "
          "**invocation** (the host's model loads it), **scan** (it runs a scan), **persistence** (a template survives "
          "into a new session), **editing** (a controlled edit is verified). "
          + " ".join(f"{ICON[k]}: {v}." for k, v in reg["test_status"].items() if k in ICON), "",
          "| Host | " + " | ".join(reg["test_stages"]) + " |", "|---|" + "---|" * len(reg["test_stages"])]
    for h in reg["hosts"]:
        L.append(f"| {h['name']} | " + " | ".join(status(h, s) for s in reg["test_stages"]) + " |")
    L += ["", "## What works at each capability level", "",
          "| Feature | Needs | " + " | ".join(c["label"] for c in reg["capability_classes"].values()) + " |",
          "|---|---|" + "---|" * len(reg["capability_classes"])]
    for f in reg["features"]:
        L.append(f"| {f['name']} | {f['needs']} | " + " | ".join(c["features"][f["id"]] for c in reg["capability_classes"].values()) + " |")
    L += ["", "## Documentation sources", "", "| Host | Source | How it was read | Facts used |", "|---|---|---|---|"]
    for h in reg["hosts"]:
        for d in h["docs"]:
            how = reg["doc_methods"][d["method"]] + (f" ({d['commit']})" if d.get("commit") else "")
            L.append(f"| {h['name']} | [{d['title']}]({d['url']}) | {how} | {d['facts']} |")
    return "\n".join(L) + "\n"


def guide(reg, h) -> str:
    L = [f"# Design DNA in {h['name']}", "",
         f"<!-- generated by python install.py docs from hosts/registry/{h['id']}.json"
         + (f" and hosts/guides/{h['id']}.md" if (GUIDES / f"{h['id']}.md").exists() else "") + " -->", ""]
    extra = GUIDES / f"{h['id']}.md"
    top, _, after = (extra.read_text(encoding="utf-8") if extra.exists() else "").partition("<!-- after-install -->")
    if top.strip():
        L += [top.strip(), ""]
    L += ["## Install", ""]
    for s in h["surfaces"]:
        cap = reg["capability_classes"][s["capability"]]
        L += [f"### {s['name']}", "", f"Method: {KIND[s['kind']]}{'' if s.get('native') else ' — not native; a labelled fallback'}. "
              f"Capability: **{cap['label']}**. {cap['summary']}", ""]
        if s["kind"] == "skill-dir" and "steps" not in s:
            L += ["```bash", "git clone https://github.com/OzyAcc/design-dna && cd design-dna",
                  f"python install.py install --target {h['id']}            # user scope: {h['skill_dirs']['user']}/{hk.skill_name()}",
                  f"python install.py install --target {h['id']} --scope project --project <your project>   # {h['skill_dirs']['project']}/{hk.skill_name()}",
                  "```", "",
                  f"Add `--dry-run` to see the changes first. The installer also runs `pip install -r requirements.txt` (skip with `--no-deps`). "
                  f"Without the installer, unzip [design-dna-skill.zip]({RELEASE}design-dna-skill.zip) into `{h['skill_dirs']['user']}/`.", ""]
        for i, st in enumerate(s.get("steps", []), 1):
            L.append(f"{i}. {st}")
        if s.get("steps"):
            L.append("")
        if s.get("package"):
            f = hk.package_kinds()[s["package"]][0]
            L += [f"Package: [{f}]({RELEASE}{f}) (or `python install.py package --target {s['package']}`).", ""]
        if s.get("limits"):
            L += [f"Limits: {s['limits']}", ""]
    if h.get("notes"):
        L += [f"Note: {h['notes']}", ""]
    if after.strip():
        L += [after.strip(), ""]
    for n in h.get("not_available", []):
        L += [f"Not available: {n}", ""]
    if "reads" in h:
        L += ["## Where the host looks", "", "| Scope | Folders this host reads (from its documentation) |", "|---|---|",
              f"| user | {', '.join(f'`{d}`' for d in h['reads']['user'])} |",
              f"| project | {', '.join(f'`{d}`' for d in h['reads']['project'])} |", "",
              "If two of these folders hold `reverse-design`, the host picks one by its own precedence rules. "
              f"`python install.py doctor --target {h['id']}` lists every copy it can see.", ""]
    L += ["## Prerequisites", ""] + [f"- {p}" for p in h["prerequisites"]] + [""]
    if any(s["kind"] in ("skill-dir", "plugin") for s in h["surfaces"]):
        L += ["## Check, update, remove", "", "```bash",
              f"python install.py doctor --target {h['id']}      # Python, packages, Chromium, store, visible copies",
              f"python install.py update --target {h['id']}      # refresh from this checkout (git pull first)",
              f"python install.py uninstall --target {h['id']}   # only unmodified copies it installed; templates are kept",
              "```", ""]
    L += ["## Try it", "", "Attach a poster or social post and ask: *Scan this design with Design DNA and save it as \"Spring Launch\".* "
          "Then: *Change only the headline to \"Made for every day\" and keep everything else.*", "",
          "## Tested here", "", "| Stage | Result | Evidence |", "|---|---|---|"]
    for st in reg["test_stages"]:
        t = h["testing"][st]
        L.append(f"| {st} | {ICON.get(t['status'], t['status'])} | {t.get('evidence', '—')} |")
    L += ["", "Untested means nobody ran it on this host from the build environment; it is not a claim that it fails.", ""]
    if h["docs"]:
        L += ["## Sources", ""] + [f"- [{d['title']}]({d['url']}) — {reg['doc_methods'][d['method']]}"
                                   + (f" ({d['commit']})" if d.get("commit") else "") + f", checked {reg['checked']}." for d in h["docs"]] + [""]
    return "\n".join(L)


def targets(reg) -> dict[Path, str]:
    out = {DOCS / "COMPATIBILITY.md": compatibility(reg)}
    for h in reg["hosts"]:
        out[DOCS / f"{h['id']}.md"] = guide(reg, h)
    text = README.read_text(encoding="utf-8")
    if BEGIN in text and END in text:
        pre, rest = text.split(BEGIN, 1)
        out[README] = pre + readme_block(reg) + rest.split(END, 1)[1]
    return out


def write_all(check=False) -> list[str]:
    reg = hk.load_registry()
    changed = []
    for path, content in targets(reg).items():
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            changed.append(str(path.relative_to(hk.ROOT)))
            if not check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content, encoding="utf-8", newline="\n")
    return changed
